In [2]:
import numpy as np
math=np.array([85, 92, 78, 90, 88])
eng=np.array([80, 75, 92, 85, 78])
sci=np.array([90, 88, 92, 80, 85])
data=np.array([math, eng, sci])
print("Data :\n",data)
#Matrix Operation
print("\n1)Matrix Operation :")
tr = np.transpose(data)
print("\ntranspose :\n",tr)
m=np.mean(data, axis=1)
print("\nMean in Row :",m)
m=np.mean(data, axis=0)
print("\nMean in Column :",m)
s=np.sum(data)
print("\nTotal marks :",s)
#Horizontal and vertical stacking of Numpy Arrays
print("\n2)Horizontal and vertical stacking of Numpy Arrays")
math2=np.array([95, 88, 90, 82, 85])
eng2=np.array([92, 85, 80, 78, 90])
sci2=np.array([88, 92, 85, 80, 90])
data2=[math2,eng2,sci2]
Hstack=np.hstack(data)
print("\nHorizontal stacking is: \n",Hstack)
Vstack=np.vstack(data2)
print("\nVertical stacking is: \n",Vstack)
#Custom sequence generation
print("\n3)Custom sequence generation")
seq=np.arange(1, 10, 2)
print("Generated Sequence",seq)
ran=np.random.randint(0, 10, 5)
print("Generated random Sequence",ran)
#Arithmatic and Statistical Operations, Mathematical Operations, BitwiseOperations

print("\n 4)Arithmatic and Statistical Operations, Mathematical Operations,Bitwise Operations ")
a=data+5
print("\nAddition :\n",a)
m=np.min(data,axis=1)
print("\nMinimum in Row :",m)
m=np.min(data,axis=0)
print("\nMinimum in Column :",m)
m=np.max(data,axis=1)
print("\nMaxmum in Row :",m)
m=np.max(data,axis=0)
print("\nMaxmum in Column :",m)
e=np.exp(data)
print("\nExponential :\n",e)
b=data&90
print("\nBitwise and :\n",b)
#Copying and viewing arrays
print("\n5)Copying and viewing arrays")
co=data.copy()
print("\nCopying arrays :\n",co)
vi=data.view()
print("\nViewing arrays :\n",vi)

Data :
 [[85 92 78 90 88]
 [80 75 92 85 78]
 [90 88 92 80 85]]

1)Matrix Operation :

transpose :
 [[85 80 90]
 [92 75 88]
 [78 92 92]
 [90 85 80]
 [88 78 85]]

Mean in Row : [86.6 82.  87. ]

Mean in Column : [85.         85.         87.33333333 85.         83.66666667]

Total marks : 1278

2)Horizontal and vertical stacking of Numpy Arrays

Horizontal stacking is: 
 [85 92 78 90 88 80 75 92 85 78 90 88 92 80 85]

Vertical stacking is: 
 [[95 88 90 82 85]
 [92 85 80 78 90]
 [88 92 85 80 90]]

3)Custom sequence generation
Generated Sequence [1 3 5 7 9]
Generated random Sequence [3 0 1 8 7]

 4)Arithmatic and Statistical Operations, Mathematical Operations,Bitwise Operations 

Addition :
 [[90 97 83 95 93]
 [85 80 97 90 83]
 [95 93 97 85 90]]

Minimum in Row : [78 75 80]

Minimum in Column : [80 75 78 80 78]

Maxmum in Row : [92 92 92]

Maxmum in Column : [90 92 92 90 88]

Exponential :
 [[8.22301271e+36 9.01762841e+39 7.49841700e+33 1.22040329e+39
  1.65163625e+38]
 [5.54062238e+34 3.7